config/routes.rb
Mapped::Application.routes.draw do

  resources :edges

  resources :nodes

  resources :conjunctions

  resources :extraneous

  resources :abreviations

  resources :procedures do
		collection do
			get 'map'
		end
  end
  
  resources :terms

end

app/models/conjunction.rb
class Conjunction < ActiveRecord::Base
end

app/controllers/conjunctions_controller.rb
class ConjunctionsController < ApplicationController
  # GET /conjunctions
  # GET /conjunctions.json
  def index
    @conjunctions = Conjunction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @conjunctions }
    end
  end

  # GET /conjunctions/1
  # GET /conjunctions/1.json
  def show
    @conjunction = Conjunction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @conjunction }
    end
  end

  # GET /conjunctions/new
  # GET /conjunctions/new.json
  def new
    @conjunction = Conjunction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @conjunction }
    end
  end

  # GET /conjunctions/1/edit
  def edit
    @conjunction = Conjunction.find(params[:id])
  end

  # POST /conjunctions
  # POST /conjunctions.json
  def create
    @conjunction = Conjunction.new(params[:conjunction])

    respond_to do |format|
      if @conjunction.save
        format.html { redirect_to @conjunction, :notice => 'Conjunction was successfully created.' }
        format.json { render :json => @conjunction, :status => :created, :location => @conjunction }
      else
        format.html { render :action => "new" }
        format.json { render :json => @conjunction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /conjunctions/1
  # PUT /conjunctions/1.json
  def update
    @conjunction = Conjunction.find(params[:id])

    respond_to do |format|
      if @conjunction.update_attributes(params[:conjunction])
        format.html { redirect_to @conjunction, :notice => 'Conjunction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @conjunction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /conjunctions/1
  # DELETE /conjunctions/1.json
  def destroy
    @conjunction = Conjunction.find(params[:id])
    @conjunction.destroy

    respond_to do |format|
      format.html { redirect_to conjunctions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/conjunctions_helper.rb
module ConjunctionsHelper
end

app/views/conjunctions/_form.html.erb
<%= form_for(@conjunction) do |f| %>
  <% if @conjunction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conjunction.errors.count, "error") %> prohibited this conjunction from being saved:</h2>

      <ul>
      <% @conjunction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conjunctions/edit.html.erb
<h1>Editing conjunction</h1>

<%= render 'form' %>

<%= link_to 'Show', @conjunction %> |
<%= link_to 'Back', conjunctions_path %>

app/views/conjunctions/index.html.erb
<h1>Listing conjunctions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conjunctions.each do |conjunction| %>
  <tr>
    <td><%= conjunction.name %></td>
    <td><%= link_to 'Show', conjunction %></td>
    <td><%= link_to 'Edit', edit_conjunction_path(conjunction) %></td>
    <td><%= link_to 'Destroy', conjunction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conjunction', new_conjunction_path %>

app/views/conjunctions/new.html.erb
<h1>New conjunction</h1>

<%= render 'form' %>

<%= link_to 'Back', conjunctions_path %>

app/views/conjunctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @conjunction.name %>
</p>


<%= link_to 'Edit', edit_conjunction_path(@conjunction) %> |
<%= link_to 'Back', conjunctions_path %>