config/routes.rb
Mapped::Application.routes.draw do

  resources :edges

  resources :nodes

  resources :conjunctions

  resources :extraneous

  resources :abreviations

  resources :procedures do
		collection do
			get 'map'
		end
  end
  
  resources :terms

end

app/models/node.rb
require 'csv'

class Node < ActiveRecord::Base
	has_many :terms, :through => :edges
	has_many :edges, :order => "weight DESC"

	def strongest
		edges = self.edges[0].term
	end

	def self.importpb
		Procedure.all.each{|proc|
			strings = proc.short_name.downcase.gsub("&","").split(" ")
			strings.each{|string|
				node = Node.find_or_create_by_name(string)
				proc.terms.each{|radlex|
					if radlex.id == 13060
						next
					end
					edges = node.edges.where(:term_id => radlex.id)
					if edges.empty?
						node.edges << Edge.create(:term_id => radlex.id, :weight => 0)
					else
						edge = edges[0]
						edge.weight = edge.weight + 1
						edge.save
					end
				}
			}
		}
	end

	def self.import#Mappings
		CSV.foreach("xrmappings.csv") do |row|
				puts row[0]
				rawstring = row[1]
				contrast = String.new
				if rawstring.index("with")
					contrast = rawstring[rawstring.index("with")..rawstring.length]
				#elsif string.index("without")
				#	contrast = string[string.index("without")..string.lenght]
				end
				strings = row[1].downcase.gsub("with","").gsub("without","").gsub("and","").gsub("contrast","").split(" ")
				strings << contrast if !contrast.empty?
				proc = Procedure.find(row[0].gsub("RPID","")) if Procedure.exists?(row[0].gsub("RPID",""))
				if proc == nil 
					#gets
					next
				else
					radlex_terms = proc.terms
					strings.each{|q|
						node = Node.find_or_create_by_name(q)
						radlex_terms.each{|radlex|
							if radlex.id == 13060
								next
							end
							edges = node.edges.where(:term_id => radlex.id)
							if edges.empty?
								node.edges << Edge.create(:term_id => radlex.id, :weight => 0)
							else
								edge = edges[0]
								edge.weight = edge.weight + 1
								edge.save
							end
						}
					}
				end
		end
	end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, :notice => 'Node was successfully created.' }
        format.json { render :json => @node, :status => :created, :location => @node }
      else
        format.html { render :action => "new" }
        format.json { render :json => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, :notice => 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :edge_id %><br />
    <%= f.number_field :edge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Edge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.name %></td>
    <td><%= node.edge_id %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>Edge:</b>
  <%= @node.edge_id %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>