config/routes.rb
Mapped::Application.routes.draw do

  resources :edges

  resources :nodes

  resources :conjunctions

  resources :extraneous

  resources :abreviations

  resources :procedures do
		collection do
			get 'map'
		end
  end
  
  resources :terms

end

app/models/abreviation.rb
class Abreviation < ActiveRecord::Base


end

app/controllers/abreviations_controller.rb
class AbreviationsController < ApplicationController
  # GET /abreviations
  # GET /abreviations.json
  def index
    @abreviations = Abreviation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @abreviations }
    end
  end

  # GET /abreviations/1
  # GET /abreviations/1.json
  def show
    @abreviation = Abreviation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @abreviation }
    end
  end

  # GET /abreviations/new
  # GET /abreviations/new.json
  def new
    @abreviation = Abreviation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @abreviation }
    end
  end

  # GET /abreviations/1/edit
  def edit
    @abreviation = Abreviation.find(params[:id])
  end

  # POST /abreviations
  # POST /abreviations.json
  def create
    @abreviation = Abreviation.new(params[:abreviation])

    respond_to do |format|
      if @abreviation.save
        format.html { redirect_to @abreviation, :notice => 'Abreviation was successfully created.' }
        format.json { render :json => @abreviation, :status => :created, :location => @abreviation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @abreviation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /abreviations/1
  # PUT /abreviations/1.json
  def update
    @abreviation = Abreviation.find(params[:id])

    respond_to do |format|
      if @abreviation.update_attributes(params[:abreviation])
        format.html { redirect_to @abreviation, :notice => 'Abreviation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @abreviation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /abreviations/1
  # DELETE /abreviations/1.json
  def destroy
    @abreviation = Abreviation.find(params[:id])
    @abreviation.destroy

    respond_to do |format|
      format.html { redirect_to abreviations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/abreviations_helper.rb
module AbreviationsHelper
end

app/views/abreviations/_form.html.erb
<%= form_for(@abreviation) do |f| %>
  <% if @abreviation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@abreviation.errors.count, "error") %> prohibited this abreviation from being saved:</h2>

      <ul>
      <% @abreviation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abreviated_name %><br />
    <%= f.text_field :abreviated_name %>
  </div>
  <div class="field">
    <%= f.label :rid %><br />
    <%= f.number_field :rid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abreviations/edit.html.erb
<h1>Editing abreviation</h1>

<%= render 'form' %>

<%= link_to 'Show', @abreviation %> |
<%= link_to 'Back', abreviations_path %>

app/views/abreviations/index.html.erb
<h1>Listing abreviations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Abreviated name</th>
    <th>Rid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @abreviations.each do |abreviation| %>
  <tr>
    <td><%= abreviation.name %></td>
    <td><%= abreviation.abreviated_name %></td>
    <td><%= abreviation.rid %></td>
    <td><%= link_to 'Show', abreviation %></td>
    <td><%= link_to 'Edit', edit_abreviation_path(abreviation) %></td>
    <td><%= link_to 'Destroy', abreviation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Abreviation', new_abreviation_path %>

app/views/abreviations/new.html.erb
<h1>New abreviation</h1>

<%= render 'form' %>

<%= link_to 'Back', abreviations_path %>

app/views/abreviations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @abreviation.name %>
</p>

<p>
  <b>Abreviated name:</b>
  <%= @abreviation.abreviated_name %>
</p>

<p>
  <b>Rid:</b>
  <%= @abreviation.rid %>
</p>


<%= link_to 'Edit', edit_abreviation_path(@abreviation) %> |
<%= link_to 'Back', abreviations_path %>