config/routes.rb
Mapped::Application.routes.draw do

  resources :edges

  resources :nodes

  resources :conjunctions

  resources :extraneous

  resources :abreviations

  resources :procedures do
		collection do
			get 'map'
		end
  end
  
  resources :terms

end

app/models/edge.rb
class Edge < ActiveRecord::Base
	belongs_to :term
	belongs_to :node

end

app/controllers/edges_controller.rb
class EdgesController < ApplicationController
  # GET /edges
  # GET /edges.json
  def index
    @edges = Edge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @edges }
    end
  end

  # GET /edges/1
  # GET /edges/1.json
  def show
    @edge = Edge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @edge }
    end
  end

  # GET /edges/new
  # GET /edges/new.json
  def new
    @edge = Edge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @edge }
    end
  end

  # GET /edges/1/edit
  def edit
    @edge = Edge.find(params[:id])
  end

  # POST /edges
  # POST /edges.json
  def create
    @edge = Edge.new(params[:edge])

    respond_to do |format|
      if @edge.save
        format.html { redirect_to @edge, :notice => 'Edge was successfully created.' }
        format.json { render :json => @edge, :status => :created, :location => @edge }
      else
        format.html { render :action => "new" }
        format.json { render :json => @edge.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /edges/1
  # PUT /edges/1.json
  def update
    @edge = Edge.find(params[:id])

    respond_to do |format|
      if @edge.update_attributes(params[:edge])
        format.html { redirect_to @edge, :notice => 'Edge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @edge.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /edges/1
  # DELETE /edges/1.json
  def destroy
    @edge = Edge.find(params[:id])
    @edge.destroy

    respond_to do |format|
      format.html { redirect_to edges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/edges_helper.rb
module EdgesHelper
end

app/views/edges/_form.html.erb
<%= form_for(@edge) do |f| %>
  <% if @edge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edge.errors.count, "error") %> prohibited this edge from being saved:</h2>

      <ul>
      <% @edge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term_id %><br />
    <%= f.number_field :term_id %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/edges/edit.html.erb
<h1>Editing edge</h1>

<%= render 'form' %>

<%= link_to 'Show', @edge %> |
<%= link_to 'Back', edges_path %>

app/views/edges/index.html.erb
<h1>Listing edges</h1>

<table>
  <tr>
    <th>Term</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @edges.each do |edge| %>
  <tr>
    <td><%= edge.term_id %></td>
    <td><%= edge.weight %></td>
    <td><%= link_to 'Show', edge %></td>
    <td><%= link_to 'Edit', edit_edge_path(edge) %></td>
    <td><%= link_to 'Destroy', edge, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Edge', new_edge_path %>

app/views/edges/new.html.erb
<h1>New edge</h1>

<%= render 'form' %>

<%= link_to 'Back', edges_path %>

app/views/edges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Term:</b>
  <%= @edge.term_id %>
</p>

<p>
  <b>Weight:</b>
  <%= @edge.weight %>
</p>


<%= link_to 'Edit', edit_edge_path(@edge) %> |
<%= link_to 'Back', edges_path %>